export {default as Websites} from './Websites'
export {default as News} from './News'
export {default as Support} from './Support'
export {default as Pricing} from './Pricing'
export {default as Features} from './Features'
export {default as Home} from './Home'
export {default as Blogs} from './Blogs'